In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.7898, 0.1397],
        [0.6721, 0.8444]]) 



In [16]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)



tensor([[0.4133, 0.0235, 0.4360],
        [0.5577, 0.0639, 0.9540]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:
print(rand_tensor.dtype)
print(rand_tensor.device)
print(rand_tensor.shape)


torch.float32
cpu
torch.Size([2, 3])


In [22]:
rand_tensor.to("cuda")

tensor([[0.4133, 0.0235, 0.4360],
        [0.5577, 0.0639, 0.9540]], device='cuda:0')

In [30]:
ones_tensor = torch.ones(4,4)
print(ones_tensor)
print("First row: {}", ones_tensor[0])
print("First column: {}", ones_tensor[:, 0])
print("Last column: {}", ones_tensor[:, -1])
ones_tensor[:, -1] = 10
print(ones_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: {} tensor([1., 1., 1., 1.])
First column: {} tensor([1., 1., 1., 1.])
Last column: {} tensor([1., 1., 1., 1.])
tensor([[ 1.,  1.,  1., 10.],
        [ 1.,  1.,  1., 10.],
        [ 1.,  1.,  1., 10.],
        [ 1.,  1.,  1., 10.]])


In [32]:
joined = torch.cat([ones_tensor, ones_tensor, ones_tensor], dim=1)
print(joined)

tensor([[ 1.,  1.,  1., 10.,  1.,  1.,  1., 10.,  1.,  1.,  1., 10.],
        [ 1.,  1.,  1., 10.,  1.,  1.,  1., 10.,  1.,  1.,  1., 10.],
        [ 1.,  1.,  1., 10.,  1.,  1.,  1., 10.,  1.,  1.,  1., 10.],
        [ 1.,  1.,  1., 10.,  1.,  1.,  1., 10.,  1.,  1.,  1., 10.]])


In [35]:
y1 = joined @ joined.T
print(joined.T)
print(y1)

tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [10., 10., 10., 10.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [10., 10., 10., 10.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [10., 10., 10., 10.]])
tensor([[309., 309., 309., 309.],
        [309., 309., 309., 309.],
        [309., 309., 309., 309.],
        [309., 309., 309., 309.]])


In [37]:
y2 = joined.matmul(joined.T)
print(y2)

tensor([[309., 309., 309., 309.],
        [309., 309., 309., 309.],
        [309., 309., 309., 309.],
        [309., 309., 309., 309.]])


In [43]:
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(ones_tensor, ones_tensor.T, out=y3)

tensor([[0.2273, 0.0960, 0.7467, 0.8630],
        [0.2068, 0.6394, 0.9883, 0.4671],
        [0.3869, 0.5961, 0.1272, 0.7879],
        [0.8453, 0.0440, 0.9779, 0.0998]])


tensor([[103., 103., 103., 103.],
        [103., 103., 103., 103.],
        [103., 103., 103., 103.],
        [103., 103., 103., 103.]])

In [44]:
z1 = ones_tensor * ones_tensor
print(z1)

tensor([[  1.,   1.,   1., 100.],
        [  1.,   1.,   1., 100.],
        [  1.,   1.,   1., 100.],
        [  1.,   1.,   1., 100.]])


In [45]:
z2 = ones_tensor.mul(ones_tensor)

z3 = torch.rand_like(ones_tensor)
torch.mul(ones_tensor, ones_tensor, out=z3)

tensor([[  1.,   1.,   1., 100.],
        [  1.,   1.,   1., 100.],
        [  1.,   1.,   1., 100.],
        [  1.,   1.,   1., 100.]])

In [47]:
agg = ones_tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(52.)
52.0 <class 'float'>


In [48]:
ones_tensor.add_(45)

tensor([[46., 46., 46., 55.],
        [46., 46., 46., 55.],
        [46., 46., 46., 55.],
        [46., 46., 46., 55.]])

In [53]:
t = torch.ones(4)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]


In [54]:
t.add_(5000)

tensor([5001., 5001., 5001., 5001.])

In [56]:
n = np.ones(5)
t = torch.from_numpy(n)

In [57]:
np.add(n, 666666, out=n)

array([666667., 666667., 666667., 666667., 666667.])